# Aula 2

## DICIONARIOS

Um dicionario é uma estrutura que permite guardar chaves e valores relacionados a essas chaves, as chaves devem ser unicas

In [23]:
months = { 
1 : "January", 
2 : "February", 
3 : "March", 
4 : "April", 
5 : "May", 
6 : "June", 
7 : "July",
8 : "August",
9 : "September", 
10 : "October", 
11 : "November",
12 : "December" } 

In [24]:
months[2]

'February'

In [25]:
months.keys()

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [26]:
months

{1: 'January',
 2: 'February',
 3: 'March',
 4: 'April',
 5: 'May',
 6: 'June',
 7: 'July',
 8: 'August',
 9: 'September',
 10: 'October',
 11: 'November',
 12: 'December'}

In [27]:
months[1] = "Jan"
print(months[1])

Jan


As chaves (keys) podem ser palavras também

In [32]:
estacoes = { 
"January": "verao", 
"February": "verao", 
"March": "outono", 
"April": "outono", 
"May": "outono", 
"June": "inverno"}

print(estacoes['March'])

outono


## TRY EXCEPT

Quando não temos certeza de que uma operação pode ser feita, utilizamos o try e except.

In [16]:
lista = [1,3,5]
try:
    objeto = lista[10]
except:
    print("elemento não existe")

elemento não existe


Existem alguns erros já mapeados (Built-In Exceptions). Um caso muito utilizado é leitura de arquivo, se por acaso não for possível ler ou abrir um arquivo, é lançada uma excessao especifica, assim como no exemplo abaixo onde a excessao "ZeroDivisionError" é lançada.

In [14]:
try:
    divisao = 1/0
except ZeroDivisionError:
    print("divisao impossivel")

divisao impossivel


Tratamento de erro é muito importante principalmente para não crashar um sistema inteiro do nada.

In [19]:
try:
    number = int(input("Digite um numero: "))

except ValueError:
    print("voce não digitou um numero")

Digite um numero: palaaavra
voce não digitou um numero


Nesse caso, sem o tratamento de erro, daria merda:

In [21]:
number = int(input("Digite um numero: "))

Digite um numero: koawka


ValueError: invalid literal for int() with base 10: 'koawka'

O FINALLY é sempre executado, mesmo que dê erro

In [22]:
try:
    divisao = 1/0
except ZeroDivisionError:
    print("divisao impossivel")
finally:
    print("da proxima vez não divida por zero")

divisao impossivel
da proxima vez não divida por zero


## FUNÇÕES

Funções servem para:
* Dividir uma tarefa complicada em tarefas mais simples
* Fácil de dividir essas tarefas menores para varios desenvolvedores
* Se vários códigos precisam de uma tarefa igual, não precisa repetir o código, é só chamar a função
* Fácil de reutilizar o codigo
* Código melhor estruturado
* Código mais facil de debugar

As funções só podem ser chamadas depois de declaradas

In [4]:
exemplo()

NameError: name 'exemplo' is not defined

In [5]:
def exemplo():
    print('oi!')

In [6]:
exemplo()

oi!


As funções podem receber parametros e retornar informação:

In [7]:
def multiplica_por_dois(numero):
    resposta = numero * 2
    return resposta

In [8]:
resultado = multiplica_por_dois(5)
print(resultado)

10


## ESCOPO DE VARIAVEIS

Escopo de uma variavel nos diz onde podemos acessar a variavel, por exemplo, na funcao multiplica_por_dois, temos duas variaveis "resposta" e "numero" as duas só podem ser acessadas dentro da própria função. Então se forem chamadas abaixo, levantarão um erro

In [9]:
numero

NameError: name 'numero' is not defined

In [10]:
resposta

NameError: name 'resposta' is not defined

Porém, eu declarei "resultado" fora da função e portanto posso acessá-lo

In [11]:
resultado

10

Assim como dentro de funções, variaveis também podem pertencer ao escopo de suas classes

## IMPORTS

Podemos utilizar códigos e funções já prontas mas para isso precisamos importar a biblioteca necessária, exemplo:

In [34]:
import numpy as np

In [33]:
import pandas as pd

para utilizar uma biblioteca basta chamar seu nome (ou o nome que voce der com "as X") e a função que deseja da mesma 

como por exemplo numpy.array([0,1]) ou, já que eu coloquei o nome de np para simplificar: np.array([0,1]

## NUMPY

Biblioteca muito utilizada para dados, principalmente para manipulação de arrays

Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays

Indexing of arrays: Getting and setting the value of individual array elements

Slicing of arrays: Getting and setting smaller subarrays within a larger array

Reshaping of arrays: Changing the shape of a given array

Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

In [36]:
lista = [0,1,2,3,4]
arr = np.array(lista)
print(arr)

[0 1 2 3 4]


In [37]:
lista + 2 #erro

TypeError: can only concatenate list (not "int") to list

In [38]:
arr + 2

array([2, 3, 4, 5, 6])

Como pode ver, em uma lista normal, +2 não funciona enquanto a array permite esse tipo de operação 

Array 2D:

In [39]:
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Também podemos obter mais informações:

In [40]:
print('Shape: ', arr2d.shape)

# dtype
print('Datatype: ', arr2d.dtype)

# size
print('Size: ', arr2d.size)

# ndim
print('Num Dimensions: ', arr2d.ndim)

Shape:  (3, 3)
Datatype:  int32
Size:  9
Num Dimensions:  2


## PANDAS